import 'package:flutter/material.dart';

var productDatalist = [
  {
    "ProductID": "1",
    "category": "iPhone",
    "details":
        "\nDynamic Island,a magical new way to\n interact with iphone.GroundBreaking \nsafety features.An innovative 48Mp\nCamera.And A16 Bionic.",
    "name": "iPhone 14 pro",
    "frondimage": "assets/iphone14pro.jpeg",
    "indeximage1": "assets/0000.PNG",
    "indeximage2": "assets/000.PNG",
    "indeximage3": "assets/00.PNG",
    "indeximage4": "assets/0.PNG",
    "indexcolor1": [Color.fromARGB(255, 12, 12, 12),Color.fromARGB(255, 208, 21, 21),],
    "indexcolor2": "",
    "indexcolor3": "",
    "indexcolor4": "",
    "image1": "assets/1.PNG",
    "image2": "assets/2.PNG",
    "image3": "assets/3.PNG",
    "image4": "assets/4.PNG",
    "image5": "assets/5.PNG",
    "image6": "assets/6.PNG",
    "image7": "assets/7.PNG",
    "image8": "assets/8.PNG",
    "image9": "assets/9.PNG",
    "image10": "assets/10.PNG",
    "image11": "assets/11.PNG",
    "phonecolor1": "",
    "phonecolor2": "",
    "phonecolor3": "",
    "phonecolor4": "",
    "Frontnote":
        "Dynamic Island,a magical new way to\n interact with iphone.'GroundBreaking \nsafety features.An innovative 48Mp\nCamera.And A16 Bionic.",
    "note1": "",
    "note2": "",
    "note3": "",
    "note4": "",
    "note5": "",
    "note6": "",
    "note7": "",
    "note8": "",
    "note9": "",
    "note10": "",
    "rate": "115323",
    "tags": "all india radio \nmalayalam \ntrivandrum\nkerala"
  },
  {
    "ProductID": "2",
    "category": "Apple watch",
    "details": "\n\n Adventure awaits",
    "name": "Apple Watch Ultra",
    "frondimage": "assets/watchultra.png",
    "indeximage1": "assets/ipads.png",
    "indeximage2": "assets/w1.PNG",
    "indeximage3": "assets/w5.PNG",
    "indeximage4": "assets/0.PNG",
    "image1": "assets/w1.PNG",
    "image2": "assets/w2.PNG",
    "image3": "assets/w3.PNG",
    "image4": "assets/w4.PNG",
    "image5": "assets/w5.PNG",
    "image6": "assets/w6.PNG",
    "image7": "assets/w7.PNG",
    "image8": "assets/w8.PNG",
    "image9": "assets/w8.PNG",
    "image10": "assets/w8.PNG",
    "image11": "assets/w8.PNG",
    "phonecolor1": "",
    "phonecolor2": "",
    "phonecolor3": "",
    "phonecolor4": "",
    "Frontnote":
        "Dynamic Island,a magical new way to\n interact with iphone.'GroundBreaking \nsafety features.An innovative 48Mp\nCamera.And A16 Bionic.",
    "note1": "",
    "note2": "",
    "note3": "",
    "note4": "",
    "note5": "",
    "note6": "",
    "note7": "",
    "note8": "",
    "note9": "",
    "note10": "",
    "rate": "115323"
  },
  {
    "ProductID": "3",
    "category": "Apple watch",
    "details": "\n\nSee what makes this Apple Watch a\ngreat deal to love.",
    "name": "Apple Watch SE",
    "frondimage": "assets/watchse.png",
    "indeximage1": "assets/ipads.png",
    "indeximage2": "assets/000.PNG",
    "indeximage3": "assets/00.PNG",
    "indeximage4": "assets/0.PNG",
    "image1": "assets/watchse/1.PNG",
    "image2": "assets/watchse/2.PNG",
    "image3": "assets/watchse/3.PNG",
    "image4": "assets/watchse/4.PNG",
    "image5": "assets/watchse/5.PNG",
    "image6": "assets/watchse/6.PNG",
    "image7": "assets/watchse/7.PNG",
    "image8": "assets/watchse/8.PNG",
    "image9": "assets/watchse/9.PNG",
    "image10": "assets/watchse/1.PNG",
    "image11": "assets/watchse.png",
    "phonecolor1": "",
    "phonecolor2": "",
    "phonecolor3": "",
    "phonecolor4": "",
    "Frontnote":
        "Dynamic Island,a magical new way to\n interact with iphone.'GroundBreaking \nsafety features.An innovative 48Mp\nCamera.And A16 Bionic.",
    "note1": "",
    "note2": "",
    "note3": "",
    "note4": "",
    "note5": "",
    "note6": "",
    "note7": "",
    "note8": "",
    "note9": "",
    "note10": "",
    "rate": "115323",
    "tags": "all india radio \nmalayalam \ntrivandrum\nkerala"
  },
  {
    "ProductID": "4",
    "category": "Apple TV",
    "details":
        "\nThe best of Tv together with the best\nof Apple.Stunning picture and sound\nplus seamless smart home controll",
    "name": "Apple TV 4K",
    "frondimage": "assets/ipadpro.png",
    "indeximage1": "assets/ipads.png",
    "indeximage2": "assets/000.PNG",
    "indeximage3": "assets/00.PNG",
    "indeximage4": "assets/0.PNG",
    "image1": "assets/w1.PNG",
    "image2": "assets/w2.PNG",
    "image3": "assets/w3.PNG",
    "image4": "assets/w4.PNG",
    "image5": "assets/w5.PNG",
    "image6": "assets/w6.PNG",
    "image7": "assets/w7.PNG",
    "image8": "assets/w8.PNG",
    "image9": "assets/w8.PNG",
    "image10": "assets/w8.PNG",
    "image11": "assets/w8.PNG",
    "phonecolor1": "",
    "phonecolor2": "",
    "phonecolor3": "",
    "phonecolor4": "",
    "Frontnote":
        "Dynamic Island,a magical new way to\n interact with iphone.'GroundBreaking \nsafety features.An innovative 48Mp\nCamera.And A16 Bionic.",
    "note1": "",
    "note2": "",
    "note3": "",
    "note4": "",
    "note5": "",
    "note6": "",
    "note7": "",
    "note8": "",
    "note9": "",
    "note10": "",
    "rate": "115323",
    "tags": "all india radio \nmalayalam \ntrivandrum\nkerala"
  },
  {
    "ProductID": "5",
    "category": "macbook",
    "details":
        "Redesigned around the M2 chip.Up to\n18 hours of battery life.Big, brilliant\nLiquid Retina display.Advanced\ncamera and audio.Four stellar\nfinishes.Take a look",
    "name": "MacBook Air with M2 ",
    "frondimage": "assets/macairm2.png",
    "indeximage1": "assets/ipads.png",
    "indeximage2": "assets/000.PNG",
    "indeximage3": "assets/00.PNG",
    "indeximage4": "assets/0.PNG",
    "image1": "assets/w1.PNG",
    "image2": "assets/w2.PNG",
    "image3": "assets/w3.PNG",
    "image4": "assets/w4.PNG",
    "image5": "assets/w5.PNG",
    "image6": "assets/w6.PNG",
    "image7": "assets/w7.PNG",
    "image8": "assets/w8.PNG",
    "image9": "assets/w8.PNG",
    "image10": "assets/w8.PNG",
    "image11": "assets/w8.PNG",
    "phonecolor1": "",
    "phonecolor2": "",
    "phonecolor3": "",
    "phonecolor4": "",
    "Frontnote":
        "Dynamic Island,a magical new way to\n interact with iphone.'GroundBreaking \nsafety features.An innovative 48Mp\nCamera.And A16 Bionic.",
    "note1": "",
    "note2": "",
    "note3": "",
    "note4": "",
    "note5": "",
    "note6": "",
    "note7": "",
    "note8": "",
    "note9": "",
    "note10": "",
    "rate": "115323",
    "tags": "all india radio \nmalayalam \ntrivandrum\nkerala"
  },
  {
    "ProductID": "6",
    "category": "Airpods",
    "details": "\n\nRebuilt from the sound up.",
    "name": "AirPods Pro",
    "frondimage": "assets/airpodpro.png",
    "indeximage1": "assets/ipads.png",
    "indeximage2": "assets/000.PNG",
    "indeximage3": "assets/00.PNG",
    "indeximage4": "assets/0.PNG",
    "image1": "assets/w1.PNG",
    "image2": "assets/w2.PNG",
    "image3": "assets/w3.PNG",
    "image4": "assets/w4.PNG",
    "image5": "assets/w5.PNG",
    "image6": "assets/w6.PNG",
    "image7": "assets/w7.PNG",
    "image8": "assets/w8.PNG",
    "image9": "assets/w8.PNG",
    "image10": "assets/w8.PNG",
    "image11": "assets/w8.PNG",
    "phonecolor1": "",
    "phonecolor2": "",
    "phonecolor3": "",
    "phonecolor4": "",
    "Frontnote":
        "Dynamic Island,a magical new way to\n interact with iphone.'GroundBreaking \nsafety features.An innovative 48Mp\nCamera.And A16 Bionic.",
    "note1": "",
    "note2": "",
    "note3": "",
    "note4": "",
    "note5": "",
    "note6": "",
    "note7": "",
    "note8": "",
    "note9": "",
    "note10": "",
    "rate": "115323",
    "tags": "all india radio \nmalayalam \ntrivandrum\nkerala"
  },
  {
    "ProductID": "7",
    "category": "iPad",
    "details":
        "\nThe Ultimate ipad experience with the\nmost advanced technology.discover\nthe most pro ipad ever",
    "name": "iPad Pro",
    "frondimage": "assets/ipads.png",
    "indeximage1": "assets/ipads.png",
    "indeximage2": "assets/000.PNG",
    "indeximage3": "assets/00.PNG",
    "indeximage4": "assets/0.PNG",
    "image1": "assets/ipad/1.PNG",
    "image2": "assets/ipad/2.PNG",
    "image3": "assets/ipad/3.PNG",
    "image4": "assets/ipad/4.PNG",
    "image5": "assets/ipad/5.PNG",
    "image6": "assets/ipad/6.PNG",
    "image7": "assets/ipad/7.PNG",
    "image8": "assets/ipad/8.PNG",
    "image9": "assets/ipad/5.PNG",
    "image10": "assets/ipad/3.PNG",
    "image11": "assets/ipad/8.PNG",
    "phonecolor1": "",
    "phonecolor2": "",
    "phonecolor3": "",
    "phonecolor4": "",
    "Frontnote":
        "Dynamic Island,a magical new way to\n interact with iphone.'GroundBreaking \nsafety features.An innovative 48Mp\nCamera.And A16 Bionic.",
    "note1": "",
    "note2": "",
    "note3": "",
    "note4": "",
    "note5": "",
    "note6": "",
    "note7": "",
    "note8": "",
    "note9": "",
    "note10": "",
    "rate": "115323",
    "tags": "all india radio \nmalayalam \ntrivandrum\nkerala"
  }
];
